services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task_management_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - task_management

    nginx:
        image: nginx:latest
        container_name: task_management_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - task_management

    db:
        image: mysql:8.0
        container_name: task_management_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: task_management
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: c
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - task_management

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: task_management_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - task_management

networks:
    task_management:

volumes:
    db_data:
